import sympy as sp

x = sp.symbols('x')
pi = sp.pi

print("1.1)", sp.integrate((x**2 + 1)**2, (x, 0, 1)))
print("1.2)", sp.integrate(sp.cos(x)**2, (x, 0, pi/2)))
print("1.3)", sp.integrate((3*x**4 + 3*x**2 + 1)/(1 + x**2), (x, -pi/4, 0)))
print("1.4)", sp.integrate(sp.exp(x/3), (x, 0, 3)))
print("1.5)", sp.integrate(sp.sqrt(sp.sin(x))*sp.cos(x), (x, 0, pi/2)))
print("1.6)", sp.integrate(1/(sp.sqrt(x) - 1), (x, 4, 9)))
print("1.7)", sp.integrate(1/(sp.exp(x) + 1), (x, 0, 1)))
print("1.8)", sp.integrate(x*sp.exp(-x), (x, 0, 1)))
print("1.9)", sp.integrate(x*sp.cos(3*x), (x, 0, pi/6)))
print("1.10)", sp.integrate(sp.log(x)/x**3, (x, 1, sp.E)))
print("1.11)", sp.integrate(sp.log(x)**3, (x, 1, sp.E)))
print("1.12)", sp.integrate(1/(2*sp.cos(x) + 3), (x, 0, pi/2)))
print("1.13)", sp.integrate(1/(x + x**2), (x, 1, 3)))
print("1.14)", sp.integrate(1/(x**2 + 2*x + 2), (x, -1, 1)))
print("1.15)", sp.integrate(1/(x + x**3), (x, 1, 2)))
print("1.16)", sp.integrate(x**3/(x**2 - 3*x + 2), (x, 0, sp.Rational(1,2))))
print("1.17)", sp.integrate(sp.sqrt(16 - x**2), (x, 0, 4)))
print("1.18)", sp.integrate(sp.cos(x)/sp.sin(x)**3, (x, pi/6, pi/2)))

print("\n")

print("1.1)", sp.Integral(sp.exp(3*x + 2), (x, 0, 1)).doit())
print("1.2)", sp.Integral((x**2 + 5)/(x**2 + 2), (x, 0, 2)).doit())
print("1.3)", sp.Integral(32*x/(x**2 + 1)**5, (x, 1, sp.sqrt(3))).doit())
print("1.4)", sp.Integral(1/(sp.exp(x) - sp.exp(-x)), (x, sp.log(2), sp.log(3))).doit())
print("1.5)", sp.Integral(sp.sin(x)/(1 - sp.cos(x))**2, (x, pi/2, pi)).doit())
print("1.6)", sp.Integral(x*sp.sin(x), (x, 0, pi/2)).doit())
print("1.7)", sp.Integral(sp.log(x**2 + x), (x, 1, 5)).doit())
print("1.8)", sp.Integral(x/(x**2 + 3*x + 2), (x, 0, 1)).doit())
print("1.9)", sp.Integral(1/(x*(x + 1)**2), (x, 1, 2)).doit())
print("1.10)", sp.Integral(sp.sin(5*x)*sp.cos(3*x), (x, 0, pi/4)).doit())
print("1.11)", sp.Integral(sp.cos(x)/(6 - 5*sp.sin(x) + sp.sin(x)**2), (x, 0, pi/2)).doit())
print("1.12)", sp.Integral(x**2*sp.sqrt(9 - x**2), (x, 0, 3)).doit())

print("\n")

print("2.1)", sp.integrate(1/(4 + x**2), (x, -sp.oo, 0)))
print("2.2)", sp.integrate(1/x**2, (x, 1, sp.oo)))
print("2.3)", sp.integrate(sp.cos(x), (x, 0, sp.oo)))
print("2.4)", sp.integrate(sp.atan(x)/(1 + x**2), (x, 0, sp.oo)))
print("2.5)", sp.integrate(1/(1 + x**2), (x, -sp.oo, sp.oo)))
print("2.6)", sp.integrate(x/sp.sqrt(x**2 + 8), (x, -sp.oo, 0)))
print("2.7)", sp.integrate(x**4/(x**5 + 1)**4, (x, 1, sp.oo)))
print("2.8)", sp.integrate(1/(x**2 + 2*x + 5), (x, -sp.oo, sp.oo)))
print("2.9)", sp.integrate(1/(x + x**3), (x, -sp.oo, -2)))

print("\n")

print("2.1)", sp.Integral(1/x, (x, 1, sp.oo)).doit())
print("2.2)", sp.Integral(1/(x**2 + 9), (x, -sp.oo, 0)).doit())
print("2.3)", sp.Integral(sp.sin(x), (x, -sp.oo, pi/2)).doit())
print("2.4)", sp.Integral(sp.exp(-5*x), (x, 0, sp.oo)).doit())
print("2.5)", sp.Integral(1/(2*x + 1)**sp.Rational(2,3), (x, -1, sp.oo)).doit())
print("2.6)", sp.Integral((x + 5)/(x*x**sp.Rational(1,3)), (x, 1, sp.oo)).doit())
print("2.7)", sp.Integral(x*sp.exp(2*x), (x, -sp.oo, sp.oo)).doit())
print("2.8)", sp.Integral(sp.exp(-x)*sp.sin(x), (x, 0, sp.oo)).doit())
print("2.9)", sp.Integral(1/(x**2 + 4*x + 9), (x, -sp.oo, sp.oo)).doit())